export const propertyDetails = {
    properties: [
        {
            postedDate:'01.09.2023',
            image:'assets/icons/house.svg',
            amount:'$9000',
            category: 'House',
            reviews: 4,
            status:'available',
        },
        {
            postedDate:'02.09.2023',
            image:'assets/icons/flat.svg',
            amount:'$6000',
            category: 'flat',
            reviews: 3,
            status:'sold',
        },
        {
            postedDate:'03.09.2023',
            image:'assets/icons/house.svg',
            amount:'$11000',
            category: 'House',
            reviews: 5,
            status:'under offer',
        },
        {
            postedDate:'01.09.2023',
            image:'assets/icons/house.svg',
            amount:'$9000',
            category: 'House',
            reviews: 4,
            status:'available',
        },
        {
            postedDate:'06.09.2023',
            image:'assets/icons/house.svg',
            amount:'$7000',
            category: 'House',
            reviews: 4,
            status:'available',
        },
        {
            postedDate:'18.09.2023',
            image:'assets/icons/house.svg',
            amount:'$9000',
            category: 'House',
            reviews: 5,
            status:'sold',
        },
        {
            postedDate:'20.09.2023',
            image:'assets/icons/house.svg',
            amount:'$13000',
            category: 'House',
            reviews: 2,
            status:'available',
        },
        {
            postedDate:'01.09.2023',
            image:'assets/icons/house.svg',
            amount:'$9000',
            category: 'House',
            reviews: 4,
            status:'available',
        },
        {
            postedDate:'01.09.2023',
            image:'assets/icons/house.svg',
            amount:'$9000',
            category: 'House',
            reviews: 4,
            status:'available',
        },
        {
            postedDate:'01.09.2023',
            image:'',
            amount:'$9000',
            category: 'flat',
            reviews: 4,
            status:'available',
        },
        {
            postedDate:'01.09.2023',
            image:'assets/icons/house.svg',
            amount:'$9000',
            category: 'House',
            reviews: 4,
            status:'available',
        },
        {
            postedDate:'01.09.2023',
            image:'assets/icons/flat.svg',
            amount:'$9000',
            category: 'flat',
            reviews: 4,
            status:'available',
        },
        {
            postedDate:'02.09.2023',
            image:'assets/icons/flat.svg',
            amount:'$6000',
            category: 'flat',
            reviews: 3,
            status:'sold',
        },
        {
            postedDate:'03.09.2023',
            image:'assets/icons/house.svg',
            amount:'$11000',
            category: 'House',
            reviews: 5,
            status:'under offer',
        },
        {
            postedDate:'01.09.2023',
            image:'assets/icons/flat.svg',
            amount:'$9000',
            category: 'flat',
            reviews: 4,
            status:'available',
        }
    ]
}